In [18]:
import pandas as pd
import sqlalchemy as sql
from sqlalchemy import create_engine
import oracledb as odb
import pyodbc as pdb
import urllib

In [19]:
engine1=sql.create_engine("oracle+oracledb://data_user:admin@localhost:1521/?service_name=freepdb1")
ocon=engine1.connect()
query='select DRIVER_ID, USER_ID, VEHICLE_YEAR, RATING, JOIN_DATE, IS_ACTIVE, VEHICLE_MAKE, LICENSE_PLATE from drivers'
dfo=pd.read_sql(query,ocon)

In [20]:
conns = urllib.parse.quote_plus(r'DRIVER={ODBC Driver 17 for SQL Server};'
                            r'SERVER=localhost\SQLEXPRESS;'
                            r'DATABASE=sample;'
                            r'Trusted_Connection=yes;')
engine=create_engine(f"mssql+pyodbc:///?odbc_connect={conns}")
query='select * from drivers'
dfs=pd.read_sql(query,engine)

c:\Users\ADMIN\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

# Approach 1: The Consolidated "Audit Trail" String (Default)

In [45]:
#dfo.head(3)
#dfo[dfo['driver_id']==1]
pks='driver_id;user_id'
pk=str.split(pks,sep=';')

dfo_dups=dfo[dfo.duplicated(keep=False)]
dfs_dups=dfs[dfs.duplicated(keep=False)]

df_src=dfo.drop_duplicates(keep='first')
df_src['join_date']=df_src['join_date'].astype('string').str[0:10]
df_tgt=dfs.drop_duplicates(keep='first')

dfo_col=set(dfo.columns)
dfs_col=set(dfs.columns)

mis_src=list(dfo_col-dfs_col)
mis_tgt=list(dfs_col-dfo_col)

com_cols=[c for c in df_src.columns if c in dfs_col and c not in pk ]
all_cols=pk+com_cols

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20884\2283986692.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_src['join_date']=df_src['join_date'].astype('string').str[0:10]

In [46]:
merged= df_src.merge(df_tgt,on=pk,how='outer',suffixes=('_src','_tgt'),indicator=True)
#df_src[df_src['driver_id']==401]
src_only=df_src[merged['_merge']=='left_only'] 
tgt_only=merged[merged['_merge']=='right_only']
comm=merged[merged['_merge']=='both']

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_20884\3693107473.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  src_only=df_src[merged['_merge']=='left_only']

In [49]:
def test_cmp():
    report_data=[]
    mis_data=[]
    for ind,row in comm.iterrows():
        report_row={pks:row[pks] for pks in pk }
        is_mis=False
        for col in com_cols:
            v1=str(row[f"{col}_src"]).strip() if pd.notnull(row[f"{col}_src"]) else ''
            v2=str(row[f"{col}_tgt"]).strip() if pd.notnull(row[f"{col}_tgt"]) else ''

            if v1 in ['NA','nan','None']: v1=''
            if v2 in ['NA','nan','None']: v2='' 

            report_row[col]=v1 
            if v1==v2:
                report_row[col]=v1   
            else:
                f"{v1} --> {v2}"
                is_mis=True
                
        report_data.append(report_row)
        if is_mis==True:
            mis_data.append(report_row)
            
    return pd.DataFrame(report_data),pd.DataFrame(mis_data)

In [53]:
test_cmp()[1]

,driver_id,user_id,vehicle_year,rating,join_date,is_active,vehicle_make,license_plate
0,2,408,2016.0,4.210000038146973,2020-12-14,1.0,Hyundai,WLW-3906

# Approach 2: The Side-by-Side Column Matrix (Pandas Native)

In [89]:
def compare_via_side_by_side():
    pks='driver_id;user_id'
    if isinstance(pks,str):
        pks=[pk.strip() for pk in pks.split(';')]

    dfo_c=dfo.drop_duplicates(subset=pks,keep='first').set_index(keys=pks)
    dfs_c=dfs.drop_duplicates(subset=pks,keep='first').set_index(keys=pks)

    comm_cols =[c for c in dfo_c.columns if c in dfs_c.columns]

    src_aligned,tgt_aligned=dfo_c[com_cols].align(dfs_c[com_cols],join='inner')

    row_mis=~(src_aligned==tgt_aligned).all(axis=1)
    src_mis=src_aligned[row_mis]
    tgt_mis=tgt_aligned[row_mis]

    cmp_matrix=pd.concat([src_mis,tgt_mis],axis=1,keys=['Src','Tgt'])

    return cmp_matrix.reset_index()

In [90]:
compare_via_side_by_side()

  driver_id user_id          Src                                           \
                    vehicle_year rating  join_date is_active vehicle_make
0         2     408         2016   4.21 2020-12-14         1      Hyundai

                         Tgt                                            \
  license_plate vehicle_year rating   join_date is_active vehicle_make
0      WLW-3906         2016   4.31  2020-12-14         0      Hyundai


  license_plate
0      WLW-3906

# Approach 3: The Row-by-Row Long Format Audit Log

In [59]:
def row_row_log():
    pks='driver_id,user_id'
    if isinstance(pks,str):
        pks=[pk.strip() for pk in pks.split(',')]

    dfs_c=dfs.drop_duplicates(subset=pks,keep='first').copy()
    dfo_c=dfo.drop_duplicates(subset=pks,keep='first').copy()

    com_cols=[col for col in dfs_c.columns if col in dfo_c and col not in pks]

    merged=dfo_c.merge(dfs_c,how='outer',indicator=True,suffixes=('_src','_tgt'),on=pks)

    only_src=merged[merged['_merge']=='left_only']
    only_tgt=merged[merged['_merge']=='right_only']
    com_rows=merged[merged['_merge']=='both']

    match_rec=[]
    log_records=[]
    for _,row in com_rows.iterrows():
        key_val="-".join([str(row[pk]) for pk in pks])
        report_row={pk:row[pk] for pk in pks}

        for col in com_cols:
            v1=str(row[f"{col}_src"]).strip() if pd.notnull(row[str(f"{col}_src")]) else ''
            v2=str(row[f"{col}_tgt"]).strip() if pd.notnull(row[str(f"{col}_tgt")]) else ''

            if v1 in ['nan','none']: v1=''
            if v2 in ['nan','none']: v2='' 

            if v1==v2:
                report_row[col]=v1
            else:
                log_records.append({
                    'key_iden':key_val,
                    'col_name':col,
                    'src':v1,
                    'tgt':v2
                })
        match_rec.append(report_row)
    return pd.DataFrame(log_records),pd.DataFrame(match_rec)

In [60]:
row_row_log()[1]

,driver_id,user_id,vehicle_make,vehicle_year,license_plate,rating,is_active
0,1,1781,Kia,2015.0,ZVJ-2140,4.099999904632568,1.0
1,2,408,Hyundai,2016.0,WLW-3906,NaN,NaN
2,3,693,Hyundai,2014.0,WEA-5140,3.809999942779541,1.0
3,4,187,Nissan,2021.0,KDE-9978,4.820000171661377,1.0
4,5,1499,Ford,2019.0,EKJ-8600,3.299999952316284,0.0
...,...,...,...,...,...,...,...
394,395,540,Chevrolet,2016.0,VXU-8147,3.1700000762939453,0.0
395,396,571,Tesla,2017.0,FBS-6111,4.940000057220459,1.0
396,397,1658,Subaru,2019.0,SMK-7631,4.559999942779541,1.0
397,398,1764,Honda,2020.0,VGV-6909,3.6600000858306885,1.0
398,399,446,Mazda,2019.0,TZD-8159,4.679999828338623,1.0

In [54]:
match_rec=[]
log_records=[]
for _,row in com_rows.iterrows():
    key_val="-".join([str(row[pk]) for pk in pks])
    report_row={pk: row[pk] for pk in pks}
    #print(key_val,report_row)
    for col in com_cols:
            print(row[f"{col}_src"])
            v1=str(f"{col}_src").strip() if pd.notnull(str(f"{col}_src")) else ''
            v2=str(f"{col}_tgt").strip() if pd.notnull(str(f"{col}_tgt")) else ''

            print(v1,v2)

Kia
vehicle_make_src vehicle_make_tgt
2015.0
vehicle_year_src vehicle_year_tgt
ZVJ-2140
license_plate_src license_plate_tgt
4.099999904632568
rating_src rating_tgt
2019-12-22 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
WLW-3906
license_plate_src license_plate_tgt
4.210000038146973
rating_src rating_tgt
2020-12-14 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2014.0
vehicle_year_src vehicle_year_tgt
WEA-5140
license_plate_src license_plate_tgt
3.809999942779541
rating_src rating_tgt
2023-07-25 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
KDE-9978
license_plate_src license_plate_tgt
4.820000171661377
rating_src rating_tgt
2020-01-11 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2019.0
vehicle_year_src vehicle_year_tgt
EKJ-8600
license_plate_src license_plate_tgt
3.299999952316284
rating_src rating_tgt
2023-07-15 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2012.0
vehicle_year_src vehicle_year_tgt
NUT-1132
license_plate_src license_plate_tgt
3.5999999046325684
rating_src rating_tgt
2022-01-30 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
LWV-0482
license_plate_src license_plate_tgt
4.309999942779541
rating_src rating_tgt
2022-11-08 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Honda
vehicle_make_src vehicle_make_tgt
2019.0
vehicle_year_src vehicle_year_tgt
TWE-2192
license_plate_src license_plate_tgt
2.6600000858306885
rating_src rating_tgt
2021-09-05 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
FGT-3745
license_plate_src license_plate_tgt
4.980000019073486
rating_src rating_tgt
2020-11-28 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
JDT-8776
license_plate_src license_plate_tgt
4.96999979019165
rating_src rating_tgt
2019-06-30 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2015.0
vehicle_year_src vehicle_year_tgt
DHP-4368
license_plate_src license_plate_tgt
4.179999828338623
rating_src rating_tgt
2020-08-13 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
PCG-7938
license_plate_src license_plate_tgt
4.710000038146973
rating_src rating_tgt
2022-02-23 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
CWU-2740
license_plate_src license_plate_tgt
3.640000104904175
rating_src rating_tgt
2021-12-23 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Honda
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
TDJ-4599
license_plate_src license_plate_tgt
3.7699999809265137
rating_src rating_tgt
2022-04-12 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
FAT-3618
license_plate_src license_plate_tgt
4.699999809265137
rating_src rating_tgt
2021-06-12 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
YNJ-1166
license_plate_src license_plate_tgt
4.630000114440918
rating_src rating_tgt
2020-04-07 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
WGZ-9299
license_plate_src license_plate_tgt
4.199999809265137
rating_src rating_tgt
2020-03-05 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
GPH-9690
license_plate_src license_plate_tgt
3.7200000286102295
rating_src rating_tgt
2020-04-24 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2014.0
vehicle_year_src vehicle_year_tgt
RKE-8092
license_plate_src license_plate_tgt
3.690000057220459
rating_src rating_tgt
2023-07-24 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2015.0
vehicle_year_src vehicle_year_tgt
LSU-0131
license_plate_src license_plate_tgt
4.210000038146973
rating_src rating_tgt
2023-02-12 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
NQD-8778
license_plate_src license_plate_tgt
3.559999942779541
rating_src rating_tgt
2020-11-05 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Honda
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
QXS-7721
license_plate_src license_plate_tgt
4.400000095367432
rating_src rating_tgt
2022-10-09 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
MSL-0178
license_plate_src license_plate_tgt
4.860000133514404
rating_src rating_tgt
2023-01-02 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
SGJ-0745
license_plate_src license_plate_tgt
4.150000095367432
rating_src rating_tgt
2020-11-26 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Honda
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
QPQ-8601
license_plate_src license_plate_tgt
4.460000038146973
rating_src rating_tgt
2019-12-19 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
ZFP-7687
license_plate_src license_plate_tgt
3.5999999046325684
rating_src rating_tgt
2021-11-18 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
AKV-7492
license_plate_src license_plate_tgt
4.449999809265137
rating_src rating_tgt
2021-04-04 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Honda
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
VTW-2839
license_plate_src license_plate_tgt
4.170000076293945
rating_src rating_tgt
2019-09-06 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
ZGV-2753
license_plate_src license_plate_tgt
4.019999980926514
rating_src rating_tgt
2023-12-27 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
JQT-8281
license_plate_src license_plate_tgt
4.460000038146973
rating_src rating_tgt
2021-03-02 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
EKG-7388
license_plate_src license_plate_tgt
4.940000057220459
rating_src rating_tgt
2021-03-23 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2015.0
vehicle_year_src vehicle_year_tgt
PXS-5753
license_plate_src license_plate_tgt
3.799999952316284
rating_src rating_tgt
2019-12-03 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
DJJ-1387
license_plate_src license_plate_tgt
4.699999809265137
rating_src rating_tgt
2022-11-08 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2017.0
vehicle_year_src vehicle_year_tgt
ZLA-5624
license_plate_src license_plate_tgt
4.96999979019165
rating_src rating_tgt
2020-10-15 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
VDH-9844
license_plate_src license_plate_tgt
5.0
rating_src rating_tgt
2020-06-28 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
PRX-9779
license_plate_src license_plate_tgt
3.9000000953674316
rating_src rating_tgt
2021-06-28 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2017.0
vehicle_year_src vehicle_year_tgt
NBS-3877
license_plate_src license_plate_tgt
3.640000104904175
rating_src rating_tgt
2023-10-24 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
HVQ-7765
license_plate_src license_plate_tgt
4.199999809265137
rating_src rating_tgt
2022-08-20 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
LQB-9046
license_plate_src license_plate_tgt
4.210000038146973
rating_src rating_tgt
2023-05-17 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
JYG-2805
license_plate_src license_plate_tgt
4.650000095367432
rating_src rating_tgt
2020-02-29 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
LNS-3589
license_plate_src license_plate_tgt
4.309999942779541
rating_src rating_tgt
2023-03-27 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2012.0
vehicle_year_src vehicle_year_tgt
ZBU-5700
license_plate_src license_plate_tgt
3.740000009536743
rating_src rating_tgt
2020-07-03 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2014.0
vehicle_year_src vehicle_year_tgt
WAY-7304
license_plate_src license_plate_tgt
4.53000020980835
rating_src rating_tgt
2023-12-05 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
MWE-3142
license_plate_src license_plate_tgt
2.940000057220459
rating_src rating_tgt
2020-07-15 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
RJU-5069
license_plate_src license_plate_tgt
3.130000114440918
rating_src rating_tgt
2020-05-11 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2012.0
vehicle_year_src vehicle_year_tgt
AKA-9589
license_plate_src license_plate_tgt
4.429999828338623
rating_src rating_tgt
2020-06-07 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2017.0
vehicle_year_src vehicle_year_tgt
CSD-3148
license_plate_src license_plate_tgt
4.260000228881836
rating_src rating_tgt
2023-12-24 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
ANY-9832
license_plate_src license_plate_tgt
3.7699999809265137
rating_src rating_tgt
2022-04-27 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2019.0
vehicle_year_src vehicle_year_tgt
EDQ-3468
license_plate_src license_plate_tgt
4.920000076293945
rating_src rating_tgt
2023-03-01 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Mazda
vehicle_make_src vehicle_make_tgt
2017.0
vehicle_year_src vehicle_year_tgt
FDZ-4700
license_plate_src license_plate_tgt
4.21999979019165
rating_src rating_tgt
2023-02-10 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
CRX-5757
license_plate_src license_plate_tgt
3.9200000762939453
rating_src rating_tgt
2020-03-04 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
YLL-0015
license_plate_src license_plate_tgt
3.9600000381469727
rating_src rating_tgt
2023-10-28 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
VEC-8751
license_plate_src license_plate_tgt
3.569999933242798
rating_src rating_tgt
2019-07-28 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
EZB-8875
license_plate_src license_plate_tgt
4.059999942779541
rating_src rating_tgt
2023-05-02 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
LEF-3745
license_plate_src license_plate_tgt
3.569999933242798
rating_src rating_tgt
2021-07-21 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
AFV-8998
license_plate_src license_plate_tgt
4.760000228881836
rating_src rating_tgt
2019-08-31 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
FSX-4586
license_plate_src license_plate_tgt
4.820000171661377
rating_src rating_tgt
2023-07-18 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
AVK-8172
license_plate_src license_plate_tgt
3.680000066757202
rating_src rating_tgt
2019-08-25 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2022.0
vehicle_year_src vehicle_year_tgt
SBC-1705
license_plate_src license_plate_tgt
4.610000133514404
rating_src rating_tgt
2023-03-26 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
GWG-7382
license_plate_src license_plate_tgt
3.940000057220459
rating_src rating_tgt
2020-07-16 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2012.0
vehicle_year_src vehicle_year_tgt
MCF-8178
license_plate_src license_plate_tgt
4.420000076293945
rating_src rating_tgt
2021-11-14 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
URN-9770
license_plate_src license_plate_tgt
2.759999990463257
rating_src rating_tgt
2020-10-26 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2019.0
vehicle_year_src vehicle_year_tgt
ERK-1201
license_plate_src license_plate_tgt
4.489999771118164
rating_src rating_tgt
2021-11-15 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
WQG-1531
license_plate_src license_plate_tgt
3.380000114440918
rating_src rating_tgt
2019-07-06 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
YJD-1235
license_plate_src license_plate_tgt
4.650000095367432
rating_src rating_tgt
2020-02-01 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
PAV-4536
license_plate_src license_plate_tgt
4.869999885559082
rating_src rating_tgt
2020-09-29 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2016.0
vehicle_year_src vehicle_year_tgt
JZL-9153
license_plate_src license_plate_tgt
4.460000038146973
rating_src rating_tgt
2020-05-23 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2014.0
vehicle_year_src vehicle_year_tgt
JAV-1475
license_plate_src license_plate_tgt
4.099999904632568
rating_src rating_tgt
2022-12-05 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Hyundai
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
LLT-4333
license_plate_src license_plate_tgt
4.579999923706055
rating_src rating_tgt
2020-07-26 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Chevrolet
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
EEW-6695
license_plate_src license_plate_tgt
4.110000133514404
rating_src rating_tgt
2023-01-09 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2018.0
vehicle_year_src vehicle_year_tgt
DCR-3876
license_plate_src license_plate_tgt
2.869999885559082
rating_src rating_tgt
2022-07-04 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2020.0
vehicle_year_src vehicle_year_tgt
LYA-2519
license_plate_src license_plate_tgt
4.650000095367432
rating_src rating_tgt
2023-01-04 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2015.0
vehicle_year_src vehicle_year_tgt
DHF-7746
license_plate_src license_plate_tgt
4.300000190734863
rating_src rating_tgt
2022-12-08 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
CAW-0839
license_plate_src license_plate_tgt
3.7300000190734863
rating_src rating_tgt
2020-08-10 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Nissan
vehicle_make_src vehicle_make_tgt
2017.0
vehicle_year_src vehicle_year_tgt
QHX-4313
license_plate_src license_plate_tgt
3.740000009536743
rating_src rating_tgt
2020-04-07 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
NQD-5496
license_plate_src license_plate_tgt
4.960000038146973
rating_src rating_tgt
2023-02-19 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Ford
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
UDK-3106
license_plate_src license_plate_tgt
4.900000095367432
rating_src rating_tgt
2022-09-10 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt
2019.0
vehicle_year_src vehicle_year_tgt
XZY-5898
license_plate_src license_plate_tgt
2.7300000190734863
rating_src rating_tgt
2021-02-04 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Kia
vehicle_make_src vehicle_make_tgt
2013.0
vehicle_year_src vehicle_year_tgt
ZUS-9379
license_plate_src license_plate_tgt
3.5199999809265137
rating_src rating_tgt
2023-11-24 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Subaru
vehicle_make_src vehicle_make_tgt
2021.0
vehicle_year_src vehicle_year_tgt
XLE-8125
license_plate_src license_plate_tgt
4.230000019073486
rating_src rating_tgt
2020-05-07 00:00:00
join_date_src join_date_tgt
1.0
is_active_src is_active_tgt
Toyota
vehicle_make_src vehicle_make_tgt
2023.0
vehicle_year_src vehicle_year_tgt
HLL-0774
license_plate_src license_plate_tgt
3.440000057220459
rating_src rating_tgt
2020-02-23 00:00:00
join_date_src join_date_tgt
0.0
is_active_src is_active_tgt
Tesla
vehicle_make_src vehicle_make_tgt

In [49]:
com_cols

['vehicle_make',
 'vehicle_year',
 'license_plate',
 'rating',
 'join_date',
 'is_active']

In [ ]:

    for col in com_cols:
        v1=str(f"{col}_src").strip() if pd.notnull(str(f"{col}_src")) else ''
        v2=str(f"{col}_tgt").strip() if pd.notnull(str(f"{col}_tgt")) else ''

        if v1 in ['nan','none']: v1=''
        if v2 in ['nan','none']: v2='' 

        if v1==v2:
            report_row[col]=v1

        else:
            log_records.append({
                'key_iden':key_val,
                'col_name':col,
                'src':v1,
                'tgt':v2
            })
    
    match_rec.append(report_row)
    
    print(log_records

(                   vehicle_year  rating  join_date  is_active vehicle_make  \
 driver_id user_id
 1         1781             2015    4.10 2019-12-22          1          Kia
 2         408              2016    4.21 2020-12-14          1      Hyundai
 3         693              2014    3.81 2023-07-25          1      Hyundai
 4         187              2021    4.82 2020-01-11          1       Nissan
 5         1499             2019    3.30 2023-07-15          0         Ford
 ...                         ...     ...        ...        ...          ...
 395       540              2016    3.17 2021-04-15          0    Chevrolet
 396       571              2017    4.94 2023-11-21          1        Tesla
 397       1658             2019    4.56 2019-12-22          1       Subaru
 398       1764             2020    3.66 2022-09-18          1        Honda
 399       446              2019    4.68 2019-06-28          1        Mazda

                   license_plate
 driver_id user_id
 1         1781         ZVJ-2140
 2         408          WLW-3906
 3         693          WEA-5140
 4         187          KDE-9978
 5         1499         EKJ-8600
 ...                         ...
 395       540          VXU-8147
 396       571          FBS-6111
 397       1658         SMK-7631
 398       1764         VGV-6909
 399       446          TZD-8159

 [399 rows x 6 columns],
                    vehicle_year  rating   join_date  is_active vehicle_make  \
 driver_id user_id
 1         1781             2015    4.10  2019-12-22          1          Kia
 2         408              2016    4.31  2020-12-14          0      Hyundai
 3         693              2014    3.81  2023-07-25          1      Hyundai
 4         187              2021    4.82  2020-01-11          1       Nissan
 5         1499             2019    3.30  2023-07-15          0         Ford
 ...                         ...     ...         ...        ...          ...
 395       540              2016    3.17  2021-04-15          0    Chevrolet
 396       571              2017    4.94  2023-11-21          1        Tesla
 397       1658             2019    4.56  2019-12-22          1       Subaru
 398       1764             2020    3.66  2022-09-18          1        Honda
 399       446              2019    4.68  2019-06-28          1        Mazda

                   license_plate
 driver_id user_id
 1         1781         ZVJ-2140
 2         408          WLW-3906
 3         693          WEA-5140
 4         187          KDE-9978
 5         1499         EKJ-8600
 ...                         ...
 395       540          VXU-8147
 396       571          FBS-6111
 397       1658         SMK-7631
 398       1764         VGV-6909
 399       446          TZD-8159

 [399 rows x 6 columns])