In [2]:
import pandas as pd
import oracledb as odb
import sqlalchemy as sql
from  sqlalchemy import create_engine

def orcl_con(table):
    engine=sql.create_engine(f"oracle+oracledb://data_user:admin@localhost:1521/?service_name=freepdb1")
    con=engine.connect()
    query= f"select * from {table}"
    df=pd.read_sql(query,con)

    return df,engine

In [3]:
import pandas as pd
import pyodbc as odbc
import urllib as ul

def ssms_con(table):
    conns = ul.parse.quote_plus(r'DRIVER={ODBC Driver 17 for SQL Server};'
                            r'SERVER=localhost\SQLEXPRESS;'
                            r'DATABASE=sample;'
                            r'Trusted_Connection=yes;')
    engine=create_engine(f"mssql+pyodbc:///?odbc_connect={conns}")
    con=engine.connect()
    query=f"select * from {table}"
    df=pd.read_sql(query,con)
    return df,engine

In [5]:
from sqlalchemy.dialects import oracle
oracle_dtypes = {
    'rating': oracle.FLOAT(),      # Uses Oracle's standard binary precision natively
    'distance': oracle.FLOAT()     
}
con=orcl_con('out_of_school_children')[1]
df=ssms_con('drivers')[0]
#df.to_sql('drivers',con,index=False,if_exists='append',dtype=oracle_dtypes)
#con.commit()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_24572\2433978384.py:11: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con=engine.connect()

In [7]:
dfo=orcl_con('out_of_school_children')[0]
dfs=ssms_con('out_of_school_children')[0]
dfo.head(2)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_24572\2433978384.py:11: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con=engine.connect()

,country,iso3_code,region,income_group,year,out_of_school_rate_total_pct,out_of_school_rate_male_pct,out_of_school_rate_female_pct,out_of_school_children_millions,rural_out_of_school_rate_pct,urban_out_of_school_rate_pct,conflict_affected
0,Uganda,UGA,Sub-Saharan Africa,Low income,2017,19.08,17.41,19.84,1.317,42.43,11.16,0
1,Uganda,UGA,Sub-Saharan Africa,Low income,2018,16.75,18.18,15.98,1.156,26.37,7.99,0

In [8]:
assert len(dfo)!=len(dfs),'count mismatch' #count

In [9]:
assert ~dfo['country'].isnull().any() , 'no null records' #null

In [10]:
assert list(dfo.columns) ==list(dfs.columns) ,'column names miamacth'

In [11]:
assert list(dfo.dtypes) ==list(dfs.dtypes) , 'schema mismatch'

In [12]:
import pytest_check as check
check.equal( dfo.duplicated().any(),False ,f'duplicate rows exist')
#dfo[dfo.duplicated()]
check.equal(dfo.duplicated().sum()!=0,True,'2.dfo have duplicate record')

True

In [13]:
df_mis=dfo.merge(dfs,how='outer',indicator=True)
df_mis1=df_mis[df_mis['_merge']!='both']

assert len(df_mis1)==2 ,'data mismatch'

In [14]:
dfo_hash=pd.util.hash_pandas_object(dfo,index=False)
dfs_hash=pd.util.hash_pandas_object(dfs,index=False)
assert dfo_hash.isin(dfs_hash).any(),'mismatch present' #use negate to find mismatches

In [15]:
print("--- STEP 1: Handling and Removing Duplicate Records ---")
dfod=dfo[dfo.duplicated(keep=False)]
dfsd=dfs[dfs.duplicated(keep=False)]
#False - will mark both records as duplicate , first/last - only first /last will be marked.
# Continue analysis with deduplicated sets
dfod_clean=dfo.drop_duplicates(keep='first').copy()
dfsd_clean=dfs.drop_duplicates(keep='first').copy()

--- STEP 1: Handling and Removing Duplicate Records ---

In [16]:
print("--- STEP 2: Handling Column Structural Lengths ---")
src_cols=set(dfo.columns)
tgt_cols=set(dfs.columns)

missing_tgt= list(src_cols-tgt_cols)
missing_src=list(src_cols-tgt_cols)
pk=[]
shared_cols=[col for col in dfod_clean.columns if col in dfsd_clean.columns and col not in pk]

merged=dfod_clean[pk+shared_cols].merge(dfsd_clean[pk+shared_cols],how='outer',indicator=True,suffixes=('_src','_tgt'),left_on='year',right_on='year')

--- STEP 2: Handling Column Structural Lengths ---

In [18]:
# Isolate missing rows
only_src_rows = merged[merged['_merge'] == 'left_only'].copy()
only_tgt_rows = merged[merged['_merge'] == 'right_only'].copy()
aligned_rows = merged[merged['_merge'] == 'both'].copy()

aligned_rows

,country_src,iso3_code_src,region_src,income_group_src,year,out_of_school_rate_total_pct_src,out_of_school_rate_male_pct_src,out_of_school_rate_female_pct_src,out_of_school_children_millions_src,rural_out_of_school_rate_pct_src,...,region_tgt,income_group_tgt,out_of_school_rate_total_pct_tgt,out_of_school_rate_male_pct_tgt,out_of_school_rate_female_pct_tgt,out_of_school_children_millions_tgt,rural_out_of_school_rate_pct_tgt,urban_out_of_school_rate_pct_tgt,conflict_affected_tgt,_merge
0,Mozambique,MOZ,Sub-Saharan Africa,Low income,2010,19.86,19.17,23.89,0.953,28.51,...,Sub-Saharan Africa,Lower middle income,13.32,11.32,15.18,4.162,20.83,4.80,1,both
1,Mozambique,MOZ,Sub-Saharan Africa,Low income,2010,19.86,19.17,23.89,0.953,28.51,...,Sub-Saharan Africa,Low income,25.92,22.45,24.97,4.043,58.32,14.15,0,both
2,Mozambique,MOZ,Sub-Saharan Africa,Low income,2010,19.86,19.17,23.89,0.953,28.51,...,Sub-Saharan Africa,Low income,20.84,21.58,19.42,2.897,32.46,6.56,1,both
3,Mozambique,MOZ,Sub-Saharan Africa,Low income,2010,19.86,19.17,23.89,0.953,28.51,...,Sub-Saharan Africa,Lower middle income,10.94,10.41,10.93,0.957,26.36,7.32,0,both
4,Mozambique,MOZ,Sub-Saharan Africa,Low income,2010,19.86,19.17,23.89,0.953,28.51,...,Sub-Saharan Africa,Lower middle income,13.84,13.05,16.32,0.976,18.94,7.00,0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76171,Singapore,SGP,East Asia & Pacific,High income,2025,0.26,0.26,0.29,0.001,0.50,...,North America,High income,0.10,0.10,0.10,0.002,0.23,0.10,0,both
76172,Singapore,SGP,East Asia & Pacific,High income,2025,0.26,0.26,0.29,0.001,0.50,...,East Asia & Pacific,High income,0.10,0.10,0.10,0.002,0.19,0.10,0,both
76173,Singapore,SGP,East Asia & Pacific,High income,2025,0.26,0.26,0.29,0.001,0.50,...,East Asia & Pacific,High income,0.10,0.10,0.12,0.005,0.21,0.10,0,both
76174,Singapore,SGP,East Asia & Pacific,High income,2025,0.26,0.26,0.29,0.001,0.50,...,East Asia & Pacific,High income,1.73,1.54,1.99,0.035,4.14,0.66,0,both
76175,Singapore,SGP,East Asia & Pacific,High income,2025,0.26,0.26,0.29,0.001,0.50,...,East Asia & Pacific,High income,0.26,0.26,0.29,0.001,0.50,0.14,0,both