In [1]:
import pandas as pd
import sqlalchemy as sql
from sqlalchemy import create_engine
import oracledb as odb
import pyodbc as pdb
import urllib

In [2]:
engine1=sql.create_engine("oracle+oracledb://data_user:admin@localhost:1521/?service_name=freepdb1")
ocon=engine1.connect()
query='select DRIVER_ID, USER_ID, VEHICLE_YEAR, RATING, JOIN_DATE, IS_ACTIVE, VEHICLE_MAKE, LICENSE_PLATE from drivers'
dfo=pd.read_sql(query,ocon)

In [3]:
conns = urllib.parse.quote_plus(r'DRIVER={ODBC Driver 17 for SQL Server};'
                            r'SERVER=localhost\SQLEXPRESS;'
                            r'DATABASE=sample;'
                            r'Trusted_Connection=yes;')
engine=create_engine(f"mssql+pyodbc:///?odbc_connect={conns}")
query='select * from drivers'
dfs=pd.read_sql(query,engine)

c:\Users\ADMIN\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

# Approach 1: The Consolidated "Audit Trail" String (Default)

In [4]:
#dfo.head(3)
#dfo[dfo['driver_id']==1]
pks='driver_id;user_id'
pk=str.split(pks,sep=';')

dfo_dups=dfo[dfo.duplicated(keep=False)]
dfs_dups=dfs[dfs.duplicated(keep=False)]

df_src=dfo.drop_duplicates(keep='first')
df_src['join_date']=df_src['join_date'].astype('string').str[0:10]
df_tgt=dfs.drop_duplicates(keep='first')

dfo_col=set(dfo.columns)
dfs_col=set(dfs.columns)

mis_src=list(dfo_col-dfs_col)
mis_tgt=list(dfs_col-dfo_col)

com_cols=[c for c in df_src.columns if c in dfs_col and c not in pk ]
all_cols=pk+com_cols

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_2680\2283986692.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_src['join_date']=df_src['join_date'].astype('string').str[0:10]

In [5]:
merged= df_src.merge(df_tgt,on=pk,how='outer',suffixes=('_src','_tgt'),indicator=True)
#df_src[df_src['driver_id']==401]
src_only=merged[merged['_merge']=='left_only']
tgt_only=merged[merged['_merge']=='right_only']
comm=merged[merged['_merge']=='both']

In [14]:
def test_cmp1():
    report_data=[]
    mis_data=[]
    for ind,row in comm.iterrows():
        report_row={pks:row[pks] for pks in pk }
        is_mis=False
        for col in com_cols:
            v1=str(row[f"{col}_src"]).strip() if pd.notnull(row[f"{col}_src"]) else ''
            v2=str(row[f"{col}_tgt"]).strip() if pd.notnull(row[f"{col}_tgt"]) else ''

            if v1 in ['NA','nan','None']: v1=''
            if v2 in ['NA','nan','None']: v2='' 

            report_row[col]=v1 
            if v1==v2:
                report_row[col]=v1   
            else:
                report_row[col]=f"{v1} --> {v2}"
                is_mis=True
                
        report_data.append(report_row)
        if is_mis==True:
            mis_data.append(report_row)
            
    return pd.DataFrame(report_data),pd.DataFrame(mis_data)

In [15]:
test_cmp1()[1]

,driver_id,user_id,vehicle_year,rating,join_date,is_active,vehicle_make,license_plate
0,1,1781,2015 --> 2015.0,4.099999904632568,2019-12-22,1 --> 1.0,Kia,ZVJ-2140
1,2,408,2016 --> 2016.0,4.210000038146973 --> 4.309999942779541,2020-12-14,1 --> 0.0,Hyundai,WLW-3906
2,2,408,2016 --> 2016.0,4.309999942779541,2020-12-14,0 --> 0.0,Hyundai,WLW-3906
3,3,693,2014 --> 2014.0,3.809999942779541,2023-07-25,1 --> 1.0,Hyundai,WEA-5140
4,4,187,2021 --> 2021.0,4.820000171661377,2020-01-11,1 --> 1.0,Nissan,KDE-9978
...,...,...,...,...,...,...,...,...
396,396,571,2017 --> 2017.0,4.940000057220459,2023-11-21,1 --> 1.0,Tesla,FBS-6111
397,397,1658,2019 --> 2019.0,4.559999942779541,2019-12-22,1 --> 1.0,Subaru,SMK-7631
398,398,1764,2020 --> 2020.0,3.6600000858306885,2022-09-18,1 --> 1.0,Honda,VGV-6909
399,399,446,2019 --> 2019.0,4.679999828338623,2019-06-28,1 --> 1.0,Mazda,TZD-8159
400,400,1933,2014 --> 2014.0,3.5799999237060547,2022-05-18,1 --> 1.0,Nissan,ZKG-1807

# Approach 2: The Side-by-Side Column Matrix (Pandas Native)

In [8]:
def test_compare_via_side_by_side():
    pks='driver_id;user_id'
    if isinstance(pks,str):
        pks=[pk.strip() for pk in pks.split(';')]

    dfo_c=dfo.drop_duplicates(subset=pks,keep='first').set_index(keys=pks)
    dfs_c=dfs.drop_duplicates(subset=pks,keep='first').set_index(keys=pks)

    comm_cols =[c for c in dfo_c.columns if c in dfs_c.columns]

    src_aligned,tgt_aligned=dfo_c[com_cols].align(dfs_c[com_cols],join='inner')

    row_mis=~(src_aligned==tgt_aligned).all(axis=1)
    src_mis=src_aligned[row_mis]
    tgt_mis=tgt_aligned[row_mis]

    cmp_matrix=pd.concat([src_mis,tgt_mis],axis=1,keys=['Src','Tgt'])

    return cmp_matrix.reset_index()

In [9]:
test_compare_via_side_by_side()

  driver_id user_id          Src                                           \
                    vehicle_year rating  join_date is_active vehicle_make
0         2     408         2016   4.21 2020-12-14         1      Hyundai

                         Tgt                                            \
  license_plate vehicle_year rating   join_date is_active vehicle_make
0      WLW-3906         2016   4.31  2020-12-14         0      Hyundai


  license_plate
0      WLW-3906

# Approach 3: The Row-by-Row Long Format Audit Log

In [10]:
def test_row_row_log():
    pks='driver_id,user_id'
    if isinstance(pks,str):
        pks=[pk.strip() for pk in pks.split(',')]

    dfs_c=dfs.drop_duplicates(subset=pks,keep='first').copy()
    dfo_c=dfo.drop_duplicates(subset=pks,keep='first').copy()

    com_cols=[col for col in dfs_c.columns if col in dfo_c and col not in pks]

    merged=dfo_c.merge(dfs_c,how='outer',indicator=True,suffixes=('_src','_tgt'),on=pks)

    only_src=merged[merged['_merge']=='left_only']
    only_tgt=merged[merged['_merge']=='right_only']
    com_rows=merged[merged['_merge']=='both']

    match_rec=[]
    log_records=[]
    for _,row in com_rows.iterrows():
        key_val="-".join([str(row[pk]) for pk in pks])
        report_row={pk:row[pk] for pk in pks}

        for col in com_cols:
            v1=str(row[f"{col}_src"]).strip() if pd.notnull(row[str(f"{col}_src")]) else ''
            v2=str(row[f"{col}_tgt"]).strip() if pd.notnull(row[str(f"{col}_tgt")]) else ''

            if v1 in ['nan','none']: v1=''
            if v2 in ['nan','none']: v2='' 

            if v1==v2:
                report_row[col]=v1
            else:
                log_records.append({
                    'key_iden':key_val,
                    'col_name':col,
                    'src':v1,
                    'tgt':v2
                })
        match_rec.append(report_row)
    return pd.DataFrame(log_records),pd.DataFrame(match_rec)

In [11]:
test_row_row_log()[1]

     driver_id  user_id vehicle_make license_plate              rating
0            1     1781          Kia      ZVJ-2140   4.099999904632568
1            2      408      Hyundai      WLW-3906                 NaN
2            3      693      Hyundai      WEA-5140   3.809999942779541
3            4      187       Nissan      KDE-9978   4.820000171661377
4            5     1499         Ford      EKJ-8600   3.299999952316284
..         ...      ...          ...           ...                 ...
395        396      571        Tesla      FBS-6111   4.940000057220459
396        397     1658       Subaru      SMK-7631   4.559999942779541
397        398     1764        Honda      VGV-6909  3.6600000858306885
398        399      446        Mazda      TZD-8159   4.679999828338623
399        400     1933       Nissan      ZKG-1807  3.5799999237060547

[400 rows x 5 columns]